### ISSUE TITLE
华擎H610

### ISSUE THREAD

**Issue by Allen5170** [abdul-royyaq/OC-ASRock-H610M-HDV-M.2#1]
哇，感谢大佬，终于看见华擎H610的信息

请问下，我现在同主板，CPU 12490F 可以吃上黑苹果吗

**Comment by abdul-royyaq** [comment]
thank you in advance,
i think it will (just) work, even with different processor and graphic card configurations but with the same board and even the same chipset, i'm not really sure it will work, but you can try it on your own system.

**Comment by Allen5170** [comment]
Wow, thanks for your answer. I'll try it myself first

**Comment by abdul-royyaq** [comment]
glad you want to try it, hope it works on your system

**Comment by yangjiaxing888** [comment]
你好，可以给个地址下载这个个efi吗？

**Comment by abdul-royyaq** [comment]
> 你好，可以给个地址下载这个个efi吗？

you can fetch this efi file by clicking the green code button then download the zip, clone with git cli
`git clone https://github.com/abdul-royyaq/OC-ASRock-H610M-HDV-M.2`
or just download from direct link [here](https://github.com/abdul-royyaq/OC-ASRock-H610M-HDV-M.2/archive/refs/heads/main.zip)

**Comment by Allen5170** [comment]
> glad you want to try it, hope it works on your system

兄弟，啥配置，试完了分享下

**Comment by abdul-royyaq** [comment]
> > glad you want to try it, hope it works on your system
> 
> 兄弟，啥配置，试完了分享下

i'm working on [shinobu-x86_64](https://github.com/abdul-royyaq/Shinobu-x86_64), i will update [readme.md](https://github.com/abdul-royyaq/OC-ASRock-H610M-HDV-M.2/blob/main/README.md) with "how to" guide soon.

**Comment by abdul-royyaq** [comment]
a simple guide has been added to [readme.md](https://github.com/abdul-royyaq/OC-ASRock-H610M-HDV-M.2/blob/main/README.md#how-to), case close.
if you have any other questions or found new issue, feel free to create a new issue thread (with the appropriate tags, of course).
